package com.swayzetrain.utility.proceduralmap.common.component;

import java.util.ArrayList;

import org.springframework.stereotype.Component;

import com.swayzetrain.utility.proceduralmap.common.enums.PostProcessedTileType;
import com.swayzetrain.utility.proceduralmap.common.enums.TileCategory;
import com.swayzetrain.utility.proceduralmap.common.model.PostProcessingDecisionTreeEntry;

@Component
public class PostProcessingDecisionTreeComponent {
	
	private ArrayList<PostProcessingDecisionTreeEntry> PPDTCollection = new ArrayList<>();
	
	public ArrayList<PostProcessingDecisionTreeEntry> getPostProcessingDecisionTreeCollection() {
		return this.PPDTCollection;
	}
	
	public PostProcessingDecisionTreeComponent() {
		//Add all of the expected results
		
		// Simple wall
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.SIMPLE_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.SIMPLE_WALL));

		
		
		// Left Upper Group wall
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_UPPER_GROUP_WALL));

		
		// Mid Upper Group wall
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.MID_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.MID_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.MID_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.MID_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.MID_UPPER_GROUP_WALL));

		
		// Right Upper Group wall
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.RIGHT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.RIGHT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.RIGHT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.RIGHT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.RIGHT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.RIGHT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.RIGHT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.RIGHT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.RIGHT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.RIGHT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.RIGHT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.RIGHT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.RIGHT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.RIGHT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.RIGHT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.RIGHT_UPPER_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.RIGHT_UPPER_GROUP_WALL));

		
		// Left Middle Group wall
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_MIDDLE_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_MIDDLE_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_MIDDLE_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_MIDDLE_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.LEFT_MIDDLE_GROUP_WALL));


		
		// Mid Middle Group wall
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.MID_MIDDLE_GROUP_WALL));

		
		// Mid Middle No Upper Left Group Wall
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.MID_MIDDLE_NO_UPPER_LEFT_GROUP_WALL));

		
		// Mid Middle No Upper Right Group Wall
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.MID_MIDDLE_NO_UPPER_RIGHT_GROUP_WALL));

		
		// Mid Middle No Bottom Left Group Wall
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.MID_MIDDLE_NO_BOTTOM_LEFT_GROUP_WALL));

		
		// Mid Middle No Bottom Right Group Wall
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.MID_MIDDLE_NO_BOTTOM_RIGHT_GROUP_WALL));

		
		// Right Middle Group wall
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.RIGHT_MIDDLE_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.RIGHT_MIDDLE_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.RIGHT_MIDDLE_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.RIGHT_MIDDLE_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.RIGHT_MIDDLE_GROUP_WALL));

		
		// Left Bottom Group wall
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.LEFT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.LEFT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.LEFT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.LEFT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.LEFT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.LEFT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.LEFT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.LEFT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.LEFT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.LEFT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.LEFT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.LEFT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.LEFT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.LEFT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.LEFT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.LEFT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.LEFT_BOTTOM_GROUP_WALL));

		
		// Mid Bottom Group wall
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.MID_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.MID_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.MID_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.MID_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.MID_BOTTOM_GROUP_WALL));

		
		// Right Bottom Group wall
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.RIGHT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.RIGHT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.RIGHT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.RIGHT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.RIGHT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.RIGHT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.RIGHT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.RIGHT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.RIGHT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.RIGHT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.RIGHT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.RIGHT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.RIGHT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.RIGHT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.RIGHT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.PATH, PostProcessedTileType.RIGHT_BOTTOM_GROUP_WALL));
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, PostProcessedTileType.RIGHT_BOTTOM_GROUP_WALL));


		
		// Bottom Left Upper Right Group Wall
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, PostProcessedTileType.BOTTOM_LEFT_UPPER_RIGHT_GROUP_WALL));

		// Upper Left Bottom Right Group Wall
		PPDTCollection.add(new PostProcessingDecisionTreeEntry(TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, TileCategory.WALL, TileCategory.PATH, TileCategory.WALL, TileCategory.WALL, PostProcessedTileType.UPPER_LEFT_BOTTOM_RIGHT_GROUP_WALL));

	}

}
